STOCKS = ["RELIANCE","HDFCBANK","ICICIBANK","BAJFINANCE","INFY",
          "TATAMOTORS","AXISBANK","SBIN","LTIM","ADANIENT",
          "KOTAKBANK","LT","MARUTI","TECHM","LICI","HINDUNILVR",
          "NTPC","BHARTIARTL","POWERGRID","ONGC","PERSISTENT",
          "DRREDDY","M&M","WIPRO","AVENUE SUPERMARTS","TRENT","POONAWALLA"]

INDICES = ["NIFTY50","MIDCPNIFTY","SENSEX"]

SCAN_INTERVAL = 300  # 5 minutes
ACCESS_TOKEN = "your_upstox_access_token"
TELEGRAM_BOT_TOKEN = "your_telegram_bot_token"
TELEGRAM_CHAT_ID = "your_chat_id"
CONFIDENCE_THRESHOLD = 65
MAX_STRIKES_ANALYZE = 10
ENABLE_SENTIMENT = False
OI_CHANGE_THRESHOLD = 10
